import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ColorsProvider } from "@/theme/useColor";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import { ClickDetector } from "@/components/click-detector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ColorsProvider>
      <TooltipProvider>
        <html lang="en">
          <body className={cn(inter.className, "apply-font-body w-full")}>
            <Navbar />
            <ClickDetector>
              <div className=" relative -mt-[5.75rem] overflow-hidden pb-16 pt-[5.75rem]">
                <div className="relative mx-auto mt-16 w-full max-w-[85rem] px-4 sm:mt-20 sm:px-6 lg:px-8 xl:mt-32 apply-font-body">
                  {children}
                </div>
              </div>
            </ClickDetector>
            <div className="container flex items-center justify-between gap-4 md:h-24 md:flex-row">
              <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
                Built by{" "}
                <a
                  href="https://github.com/fozuzip"
                  target="_blank"
                  rel="noreferrer"
                  className="font-medium underline underline-offset-4"
                >
                  George Pittas
                </a>
                . Inspired by by{" "}
                <a
                  href="https://www.realtimecolors.com"
                  target="_blank"
                  rel="noreferrer"
                  className="font-medium underline underline-offset-4"
                >
                  Realtime Colors
                </a>
                .
              </p>
              <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
                The source code is available on{" "}
                <a
                  href="https://github.com/fozuzip/theme-wizard"
                  target="_blank"
                  rel="noreferrer"
                  className="font-medium underline underline-offset-4"
                >
                  GitHub
                </a>
                .
              </p>
            </div>
          </body>
        </html>
      </TooltipProvider>
    </ColorsProvider>
  );
}

// DONE: Undo / Redo functionality
// DONE: Lock Colors
// DONE: Randomize Colors
// DONE: Export Colors

// DONE: Light / Dark mode

// DONE: Background Color Select Component

// DONE: Font Select Functionality ?

// TODO: Tour How it works / Choose Main Colors / Typography Inputs / etc ... / Test it out

// TODO: Footer with links ...

// DONE: Fix Navbar flickering

// TODO: Add toolbars with Short desc and hotkeys on every button
