import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { TooltipProvider } from "@/components/ui/tooltip";
import { ColorsProvider } from "@/theme/useColor";
import { Navbar } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorsProvider>
          <TooltipProvider>
            <Navbar />

            <div className=" relative -mt-[5.75rem] overflow-hidden pb-16 pt-[5.75rem]">
              <div className="relative mx-auto mt-16 w-full max-w-[85rem] px-4 sm:mt-20 sm:px-6 lg:px-8 xl:mt-32">
                {children}
              </div>
            </div>
          </TooltipProvider>
        </ColorsProvider>
      </body>
    </html>
  );
}

// DONE: Undo / Redo functionality
// DONE: Lock Colors
// TODO: Randomize Colors
// TODO: Export Colors

// DONE: Light / Dark mode

// DONE: Background Color Select Component

// TODO: Font Select Functionality ?

// TODO: Tour How it works / Choose Main Colors / Typography Inputs / etc ... / Test it out

// TODO: Footer with links ...

// TODO: Fix Navbar flickering

// TODO: Add toolbars with Short desc and hotkeys on every button
